/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./src/views/about.vue')['default']
    Axios: typeof import('./src/views/axios.vue')['default']
    Children1: typeof import('./src/views/homeView/children1.vue')['default']
    Children2: typeof import('./src/views/homeView/children2.vue')['default']
    copy: typeof import('./src/views/homeView/children1 copy.vue')['default']
    DeptSet: typeof import('./src/views/setting/deptSet.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCascader: typeof import('element-plus/es')['ElCascader']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Home: typeof import('./src/views/homeView/home.vue')['default']
    HomeView: typeof import('./src/views/homeView/homeView.vue')['default']
    IconHomeCompany: typeof import('~icons/home/company')['default']
    IconIcBaseline5g: typeof import('~icons/ic/baseline5g')['default']
    IconIcBaseline5kPlus: typeof import('~icons/ic/baseline5k-plus')['default']
    MainMsg: typeof import('./src/views/homeView/mainMsg.vue')['default']
    PersonSet: typeof import('./src/views/setting/personSet.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Test2: typeof import('./src/views/test2.vue')['default']
    Vuex: typeof import('./src/views/vuex.vue')['default']
  }
}
